const Images = [ 
{
  img:'../img/halcon.png',
  link:'https://www.halconviajes.com/',
},
{
  img:'../img/geomoon.png',
  link:'https://www.geomoon.com/',
},
{
  img:'../img/puro.png',
  link:'https://www.purohotel.com/es/boutique-hotel-palma/'
},
{
  img:'../img/ferrer.png',
  link:'https://www.ferrerhotels.com/es/'
},
{
  img:'../img/w2fly.png',
  link:'https://www.w2fly.es/es-es',
},
{
  img:'../img/ubico.png',
  link:'https://www.halconviajes.com/',
},
{
  img:'../img/icarion.png',
  link:'https://www.icarion.es/',
},
{
  img:'../img/flowo.png',
  link:'https://www.flowo.com/',
},
{
  img:'../img/enorth.png',
  link:'https://www.e-northsafaris.com/en-en',
},
]

export default Images;